title: Jiyoon Oh
description: AI & Data Enthusiast
site_title: "@askjiyun.github.io"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: askjiyun
blog_url: https://www.nagekar.com
email: jynoh825@gmail.com

# absolute or relative
profile_picture: assets/images/jy.jpeg

# Google Analytics ID
google_analytics:
